name: dotnet test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 6.0
            
      - name: Install dependencies
        run: dotnet restore

      - name: Build dot net
        run: dotnet build --configuration Release SimpleCSharpProject/SimpleCSharpProject.csproj
    
      - name: Test with dotnet
        run: dotnet test --configuration Release --no-build SimpleCSharpProject.Test/SimpleCSharpProject.Test.csproj
  
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results          
          path: TestResults
